// Engineering Online Campus — Master Academic Layer
// Purpose: turn the catalog into a real university-style curriculum with prerequisites,
// workload, outcomes, labs, assessments, projects, and explicit source routes.
(function(){
  const NPTEL='https://www.nptel.ac.in/courses';
  const OCW='https://ocw.mit.edu/search/';
  const q=s=>encodeURIComponent(String(s));
  const src=(provider,title,url,kind='FREE-FULL')=>({provider,title,url,kind});

  window.CAMPUS_ACADEMIC = {
    degree:{
      title:'Integrated Engineering Mastery Program',
      model:'University-style self-study degree',
      semesters:8,
      normalLoad:'8–12 focused hours/week during a normal self-study term; electives are selected rather than all completed.',
      rule:'Core + depth + laboratory + design + systems integration + professional practice + capstone.'
    },

    semesterPlan:[
      {id:1,name:'Year 1 · Semester 1',theme:'Engineering Foundations',required:['MTH101','PHY101','CHE101','PRG101'],electiveBuckets:['MATH-E01','COMP-E01','PRO-E03'],outputs:['engineering calculation notebook','Python scientific-computing mini project','physics/measurement lab report']},
      {id:2,name:'Year 1 · Semester 2',theme:'Mechanics, Circuits & Civil Orientation',required:['MEC201','ELC201'],recommended:['CIV-E01','ME-E02','EE-E01'],outputs:['free-body/static analysis portfolio','DC/AC circuit lab','structural analysis mini-model']},
      {id:3,name:'Year 2 · Semester 1',theme:'Materials, Solids, Thermal & Civil Depth',required:['MAT301','THM401'],recommended:['CIV-E11','CIV-E16','ME-E13'],outputs:['mechanics-of-materials test report','thermodynamic cycle analysis','soil/structure design memo']},
      {id:4,name:'Year 2 · Semester 2',theme:'Design, Electronics & Structural Engineering',required:['MDE501','ELC301'],recommended:['CIV-E03','CIV-E05','EE-E06','ME-E04'],outputs:['machine-element design','analog/digital electronics lab','RC/steel member design']},
      {id:5,name:'Year 3 · Semester 1',theme:'Power, Control, Measurement & DAQ',required:['PWR401','CTL402','INS403'],recommended:['EE-E10','CTL-E01','CTL-E08'],outputs:['motor-drive simulation','closed-loop controller','sensor calibration + uncertainty report']},
      {id:6,name:'Year 3 · Semester 2',theme:'Mechatronics, Embedded & Manufacturing',required:['MCH501','EMB501','MFG501'],recommended:['ROB-E01','MFG-E03','EE-E25'],outputs:['microcontroller machine','PLC/mechatronics cell','manufacturing process plan']},
      {id:7,name:'Year 4 · Semester 1',theme:'Robotics, Simulation & Systems Engineering',required:['ROB601','SYS601','SIM601'],recommended:['ROB-E03','SYS-E03','ME-E16','CIV-E08'],outputs:['robotics integration demo','system requirements + architecture','validated FEA/CFD case study']},
      {id:8,name:'Year 4 · Semester 2',theme:'Specialization, Professional Practice & Capstone',required:['PRO701','CAP801'],recommended:['EV601','HVAC501','FLP501','CIV-E32','EE-E18'],outputs:['engineering decision memo','specialization project','multidisciplinary capstone/thesis']}
    ],

    core:{
      MTH101:{title:'Engineering Mathematics & Numerical Thinking',credits:4,prereq:[],modules:['Functions, algebra & trigonometry','Single-variable calculus','Multivariable calculus','Linear algebra','ODEs','Numerical methods','Probability & statistics','Optimization basics'],labs:['Python numerical notebook','MATLAB numerical comparison'],assessment:['weekly problem sets','midterm','numerical mini-project','final exam'],sources:[src('NPTEL','Engineering Mathematics / Advanced Engineering Mathematics',NPTEL+'?q='+q('engineering mathematics'))]},
      PHY101:{title:'Engineering Physics',credits:4,prereq:['MTH101'],modules:['Mechanics','Oscillations & waves','Electricity & magnetism','Thermal physics','Optics','Modern physics'],labs:['motion experiment','circuits/fields observation','optics report'],assessment:['problem sets','lab reports','midterm','final'],sources:[src('NPTEL','Engineering Physics',NPTEL+'?q='+q('engineering physics'))]},
      CHE101:{title:'Engineering Chemistry & Materials Science',credits:3,prereq:['PHY101'],modules:['Atomic/molecular structure','Thermodynamics','Electrochemistry','Corrosion','Polymers','Metals','Ceramics','Composites'],labs:['materials identification','corrosion mini-study'],assessment:['problem sets','lab','design memo','final'],sources:[src('NPTEL','Engineering Chemistry',NPTEL+'?q='+q('engineering chemistry'))]},
      PRG101:{title:'Engineering Programming & Scientific Computing',credits:4,prereq:['MTH101'],modules:['Python fundamentals','NumPy/SciPy','data structures','files/Git','MATLAB','C/C++ fundamentals','numerical algorithms','visualization'],labs:['data-analysis notebook','numerical solver','Git-based engineering repo'],assessment:['coding exercises','two mini-projects','final computational project'],sources:[src('NPTEL','Programming / Python for engineers',NPTEL+'?q='+q('python programming engineering'))]},
      MEC201:{title:'Mechanics & Dynamics',credits:4,prereq:['MTH101','PHY101'],modules:['Vectors','Free-body diagrams','Equilibrium','Trusses/frames','Friction','Kinematics','Particle dynamics','Rigid-body dynamics','Energy/momentum'],labs:['statics calculation notebook','motion simulation'],assessment:['problem sets','midterm','design analysis','final'],sources:[src('NPTEL','Engineering Mechanics / Mechanics of Materials',NPTEL+'?q='+q('engineering mechanics statics dynamics'))]},
      MAT301:{title:'Materials & Mechanics of Materials',credits:4,prereq:['MEC201','CHE101'],modules:['Stress/strain','Axial loading','Bending','Torsion','Combined loading','Failure theories','Material selection','Fatigue/fracture introduction'],labs:['material test interpretation','beam test/FEA correlation'],assessment:['problem sets','design report','midterm','final'],sources:[src('NPTEL','Mechanics of Materials, IIT Madras', 'https://nptel.ac.in/courses/105106172'),src('NPTEL','Mechanics of Materials archive', 'https://archive.nptel.ac.in/noc/courses/noc18/SEM1/noc18-ce04/') ]},
      THM401:{title:'Thermodynamics, Heat Transfer & Fluids',credits:5,prereq:['MTH101','PHY101'],modules:['Thermodynamic systems','First/second law','Entropy/exergy','Power/refrigeration cycles','Heat conduction','Convection','Radiation','Fluid statics','Control volumes','Internal/external flow'],labs:['cycle model','heat-transfer calculation','pipe-loss calculation'],assessment:['weekly problems','midterm','thermal design project','final'],sources:[src('NPTEL','Engineering Thermodynamics, IIT Kanpur','https://www.nptel.ac.in/courses/101104063'),src('NPTEL','Conduction and Convection Heat Transfer','https://www.nptel.ac.in/courses/112105271'),src('NPTEL','Introduction to Fluid Mechanics, IIT Kharagpur','https://www.nptel.ac.in/courses/112105269')]},
      MDE501:{title:'Advanced Mechanical Design',credits:5,prereq:['MEC201','MAT301','PRG101'],modules:['Machine elements','Shafts/bearings/gears','GD&T','Design for manufacture','Design for assembly','Materials selection','FEA introduction','Optimization','Design reviews'],labs:['CAD assembly','FEA verification','tolerance stack-up'],assessment:['design calculations','CAD package','design review','capstone-style project'],sources:[src('NPTEL','Machine Design / Mechanical Design',NPTEL+'?q='+q('machine design'))]},
      ELC201:{title:'Circuit Analysis',credits:4,prereq:['MTH101','PHY101'],modules:['KCL/KVL','network theorems','transients','AC steady state','frequency response','three-phase basics','power/energy','SPICE simulation'],labs:['SPICE DC/AC lab','RC/RL transient lab','three-phase study'],assessment:['problem sets','lab reports','midterm','final'],sources:[src('NPTEL','Introduction to Electrical Engineering, IIT Delhi','https://www.nptel.ac.in/courses/108102185')]},
      ELC301:{title:'Electronics & Digital Systems',credits:5,prereq:['ELC201'],modules:['Diodes','BJTs/MOSFETs','op-amps','feedback','digital logic','combinational/sequential systems','ADC/DAC','interfacing'],labs:['rectifier','op-amp','counter/state-machine','ADC/DAC demo'],assessment:['labs','design exercise','midterm','final'],sources:[src('NPTEL','Introduction to Electrical Engineering', 'https://www.nptel.ac.in/courses/108102185')]},
      PWR401:{title:'Power Electronics & Electric Drives',credits:4,prereq:['ELC201','ELC301'],modules:['Power semiconductor devices','rectifiers','DC-DC converters','inverters','motor fundamentals','PWM','electric drives','thermal design'],labs:['converter simulation','DC motor drive','inverter study'],assessment:['simulation lab','drive design','midterm','final'],sources:[src('NPTEL','Power Electronics / Drives',NPTEL+'?q='+q('power electronics electric drives'))]},
      CTL402:{title:'Control Systems & System Dynamics',credits:5,prereq:['MTH101','ELC201','MEC201'],modules:['Dynamic modeling','Laplace','transfer functions','time response','stability','root locus','Bode/Nyquist','PID','state space'],labs:['MATLAB/Simulink model','PID tuning','stability analysis'],assessment:['problem sets','control lab','midterm','design project','final'],sources:[src('NPTEL','Control Engineering, IIT Bombay','https://www.nptel.ac.in/courses/108101037'),src('NPTEL','Control systems archive','https://onlinecourses-archive.nptel.ac.in/noc18_ee41/preview')]},
      INS403:{title:'Measurement, Instrumentation & Data Acquisition',credits:4,prereq:['ELC301','CTL402'],modules:['measurement systems','sensor physics','signal conditioning','DAQ','sampling','uncertainty','calibration','metrology'],labs:['sensor calibration','DAQ acquisition','uncertainty budget'],assessment:['lab notebook','calibration report','DAQ project','final practical'],sources:[src('NPTEL','Instrumentation / Measurement',NPTEL+'?q='+q('instrumentation measurement data acquisition'))]},
      MCH501:{title:'Mechatronics Systems',credits:5,prereq:['MDE501','ELC301','CTL402','INS403'],modules:['system integration','actuators','sensors','mechanisms','control','embedded','machine safety','integration testing'],labs:['electromechanical subsystem','integration test plan'],assessment:['design reviews','integration demo','technical report'],sources:[src('NPTEL','Mechatronics / Design of Mechatronic Systems',NPTEL+'?q='+q('mechatronics design mechatronic systems'))]},
      EMB501:{title:'Embedded Systems',credits:5,prereq:['PRG101','ELC301','INS403'],modules:['MCU architecture','C/C++','GPIO','timers','interrupts','ADC/DAC','UART/I2C/SPI/CAN','RTOS concepts'],labs:['sensor node','motor controller','CAN/UART network'],assessment:['coding labs','embedded project','verification report'],sources:[src('NPTEL','Embedded Systems',NPTEL+'?q='+q('embedded systems'))]},
      ROB601:{title:'Robotics: Kinematics to Autonomy',credits:5,prereq:['MEC201','CTL402','EMB501','MTH101'],modules:['rigid transformations','DH parameters','FK/IK','Jacobians','dynamics','trajectory generation','motion planning','perception','ROS 2 integration'],labs:['robot kinematics notebook','ROS 2 simulation','planner/perception demo'],assessment:['problem sets','robotics lab','integration demo','final project'],sources:[src('NPTEL','Robotics, IIT Bombay','https://nptel.ac.in/courses/112101098'),src('NPTEL','Robotics and Control: Theory and Practice','https://nptel.ac.in/courses/107107289')]},
      SYS601:{title:'Engineering Systems Development',credits:4,prereq:['MCH501','CTL402'],modules:['stakeholders','requirements','architecture','interfaces','trade studies','risk','verification','validation','configuration management'],labs:['requirements baseline','architecture model','verification matrix'],assessment:['SRR','PDR','V&V plan','system report'],sources:[src('MIT OCW','Systems Engineering / engineering systems',OCW+'?q='+q('systems engineering'))]},
      MFG501:{title:'Manufacturing, Metrology & Quality',credits:4,prereq:['MDE501','INS403'],modules:['manufacturing processes','machining','forming','joining','additive','tolerances','metrology','quality engineering','process capability'],labs:['process plan','CNC/toolpath exercise','measurement study'],assessment:['process plan','quality report','manufacturing project'],sources:[src('NPTEL','Manufacturing Processes',NPTEL+'?q='+q('manufacturing processes'))]},
      SIM601:{title:'Simulation, FEA/CFD & Digital Twins',credits:5,prereq:['MAT301','THM401','PRG101'],modules:['governing equations','discretization','meshing','BCs','verification','validation','FEA','CFD','model reduction','digital twins'],labs:['FEA convergence study','CFD verification','model-vs-data comparison'],assessment:['simulation reports','verification/validation memo','digital-twin project'],sources:[src('NPTEL','Computational Fluid Dynamics',NPTEL+'?q='+q('computational fluid dynamics')),src('NPTEL','Finite Element Analysis',NPTEL+'?q='+q('finite element analysis'))]},
      PRO701:{title:'Engineering Economics, Project Management & Ethics',credits:3,prereq:[],modules:['engineering economics','cost estimation','NPV/IRR','scheduling','risk','contracts','ethics','technical communication','sustainability'],labs:['cost model','project schedule','risk register'],assessment:['decision memo','schedule','ethics case','final'],sources:[src('NPTEL','Engineering Economic Analysis',NPTEL+'?q='+q('engineering economic analysis'))]},
      CAP801:{title:'Multidisciplinary Engineering Capstone / Thesis',credits:8,prereq:['SYS601','SIM601','PRO701'],modules:['problem definition','literature review','requirements','concept selection','detailed design','prototype/simulation','verification/validation','technical writing','defense'],labs:['design-build-test cycle','formal verification','final presentation'],assessment:['proposal','PDR','prototype/simulation','final report','oral defense'],sources:[src('MIT OCW','Capstone / design project ecosystem',OCW+'?q='+q('engineering design capstone'))]}
    },

    civilExpansion:[
      {id:'CIV101',title:'Civil Engineering Foundations',credits:3,prereq:['MTH101','PHY101'],source:src('NPTEL','Introduction to Civil Engineering Profession, IIT Madras','https://www.nptel.ac.in/courses/105106201'),modules:['civil disciplines','materials','structures','water','geotechnical','transportation','construction','BIM','sustainability'],output:'civil engineering systems map'},
      {id:'CIV201',title:'Structural Analysis I',credits:4,prereq:['MEC201','MAT301'],source:src('NPTEL','Structural Analysis - I','https://onlinecourses-archive.nptel.ac.in/noc17_ce25/preview'),modules:['determinate structures','deflection','virtual work','influence lines','energy methods'],output:'full structural analysis portfolio'},
      {id:'CIV301',title:'Reinforced Concrete Design',credits:5,prereq:['MAT301','CIV201'],source:src('NPTEL','Design of Reinforced Concrete Structures, IIT Kharagpur','https://www.nptel.ac.in/courses/105105105'),modules:['materials','flexure','shear','slabs','columns','footings','torsion','multi-storey frames','detailing'],output:'RC frame design package'},
      {id:'CIV401',title:'Geotechnical Engineering I — Soil Mechanics',credits:4,prereq:['MEC201','MTH101'],source:src('NPTEL','Geotechnical Engineering - 1, IIT Bombay','https://www.nptel.ac.in/courses/105101201'),modules:['soil phase relations','classification','permeability','seepage','consolidation','shear strength','slope stability'],output:'soil investigation + design report'},
      {id:'CIV402',title:'Geotechnical Engineering II — Foundations',credits:4,prereq:['CIV401'],source:src('NPTEL','Foundation Engineering, IIT Kharagpur','https://www.nptel.ac.in/courses/105105185'),modules:['shallow foundations','bearing capacity','settlement','piles','lateral loads','site constraints'],output:'foundation design package'},
      {id:'CIV501',title:'Hydraulics & Hydrology',credits:5,prereq:['THM401','MTH101'],source:src('NPTEL','Fluid Mechanics / Hydraulics',NPTEL+'?q='+q('hydraulics hydrology civil engineering')),modules:['pipe flow','open channels','hydrology','rainfall-runoff','floods','water systems'],output:'water-system analysis'},
      {id:'CIV601',title:'Transportation Engineering',credits:4,prereq:['MTH101','PRG101'],source:src('NPTEL','Transportation Engineering',NPTEL+'?q='+q('transportation engineering highway traffic')),modules:['traffic flow','highways','pavements','intersection analysis','transport planning'],output:'corridor/traffic study'},
      {id:'CIV602',title:'Environmental Engineering',credits:4,prereq:['CHE101','CIV501'],source:src('NPTEL','Environmental Engineering',NPTEL+'?q='+q('environmental engineering water wastewater')),modules:['water quality','drinking-water treatment','wastewater','air pollution','solid waste','sustainability'],output:'treatment-system design'},
      {id:'CIV701',title:'Digital Construction, BIM & 4D/5D',credits:4,prereq:['CIV301','PRO701'],source:src('NPTEL','BIM / Digital Construction',NPTEL+'?q='+q('BIM construction digital construction')),modules:['BIM coordination','clash detection','4D','5D','quantity takeoff','information management'],output:'coordinated BIM construction plan'}
    ],

    electiveSourcePolicy:{
      rule:'Every elective must be either (A) a directly linked complete course from the personal Udemy/Coursera library, or (B) a directly linked complete free university course. A generic catalog page is allowed only as a temporary research route and is visibly labelled "needs title verification".',
      preferredFree:['NPTEL/SWAYAM course','MIT OpenCourseWare full course','Other university open course with lectures/notes/assignments'],
      forbidden:['paid-only course not in personal library','YouTube playlist with no academic structure when a full course exists elsewhere','generic search result presented as if it were a verified course']
    }
  };

  // Build deterministic title-search routes for all catalog items that still need a title-specific audit.
  const base=window.CAMPUS_ACADEMIC.electiveSourcePolicy;
  window.campusResolveElectiveSource=function(item){
    if(!item) return null;
    if(item.sourceUrl && item.sourceType==='Verified title-specific source') return item.sourceUrl;
    return NPTEL+'?q='+q(item.title);
  };
})();
