window.COURSE_LIBRARY = [
['CRS-065','Fusion 360 Essential Training','CAD / BIM Tools','Software Lab','Software Lab','LinkedIn Learning','Nick Kloski','https://www.linkedin.com/learning/fusion-360-essential-training-2'],
['CRS-062','Introduction to CAD — Parts, Assemblies, Drawings','CAD / BIM Tools','Core','Software Lab','Onshape Learning','Onshape','https://learn.onshape.com/learn/learning-path/introduction-to-cad'],
['CRS-067','Navisworks Essential Training 2023','CAD / BIM Tools','Work Laptop','Software Lab','LinkedIn Learning','Eric Wing','https://www.linkedin.com/learning/navisworks-essential-training-2023'],
['CRS-063','Onshape Fundamentals: CAD','CAD / BIM Tools','Practice','Software Lab','Onshape Learning','Onshape','https://learn.onshape.com/courses/onshape-fundamentals-cad'],
['CRS-066','Revit 2025 Essential Training for Structure','CAD / BIM Tools','Work Laptop','Software Lab','LinkedIn Learning','Eric Wing','https://www.linkedin.com/learning/revit-2025-essential-training-for-structure-imperial-and-metric'],
['CRS-064','Self-paced Learning for Fusion','CAD / BIM Tools','Core','Software Lab','Autodesk Official','Autodesk','https://www.autodesk.com/learn/ondemand/collection/self-paced-learning-for-fusion'],
['CRS-006','30 Days of Python | Unlock your Python Potential','STEM Core','Practice','Stage 1','Udemy - مكتبتك','Justin Mitchel','https://www.udemy.com/course/30-days-of-python/'],
['CRS-001','Basic Engineering Mathematics','STEM Core','Core','Stage 1','Coursera','BITS Pilani','https://www.coursera.org/learn/basic-mathematics-engineering'],
['CRS-002','Calculus for Engineers','STEM Core','Core','Stage 1','Coursera','HKUST','https://www.coursera.org/learn/calculus-for-engineers'],
['CRS-005','General Chemistry','STEM Core','Core','Stage 1','Coursera','Rice University','https://www.coursera.org/learn/general-chemistry'],
['CRS-004','General Physics','STEM Core','Core','Stage 1','Coursera','BITS Pilani','https://www.coursera.org/learn/general-physics-odc'],
['CRS-008','MATLAB Essential Training','STEM Core','Software Lab','Stage 1','LinkedIn Learning','Curt Frye','https://www.linkedin.com/learning/matlab-essential-training'],
['CRS-007','MATLAB/SIMULINK Bible | Go From Zero to Hero + ChatGPT!','STEM Core','Practice','Stage 1','Udemy - مكتبتك','Ryan Ahmed','https://www.udemy.com/course/matlabsimulink-biblego-from-zero-to-hero/'],
['CRS-003','Matrix Algebra for Engineers','STEM Core','Core','Stage 1','Coursera','HKUST','https://www.coursera.org/learn/matrix-algebra-engineers'],
['CRS-010','Applications in Engineering Mechanics','Mechanical + Civil Core','Core','Stage 2','Coursera','Georgia Tech','https://www.coursera.org/learn/engineering-mechanics-statics-2'],
['CRS-015','AutoCAD 2026 Essential Training','Mechanical + Civil Core','Software Lab','Stage 2','LinkedIn Learning','Shaun Bryant','https://www.linkedin.com/learning/autocad-2026-essential-training'],
['CRS-011','BIM Fundamentals for Engineers','Mechanical + Civil Core','Core','Stage 2','Coursera','National Taiwan University','https://www.coursera.org/learn/bim-fundamentals'],
['CRS-014','Civil Site Engineer Mastery in Building Construction','Mechanical + Civil Core','Practice','Stage 2','Udemy - مكتبتك','Akshay Kamath','https://www.udemy.com/course/construction-methodology-and-site-execution/'],
['CRS-013','Engineering Mechanics: Statics','Mechanical + Civil Core','Practice','Stage 2','Udemy - مكتبتك','Cherish Qualls','https://www.udemy.com/course/engineering-mechanics-statics/'],
['CRS-009','Introduction to Engineering Mechanics','Mechanical + Civil Core','Core','Stage 2','Coursera','Georgia Tech','https://www.coursera.org/learn/engineering-mechanics-statics'],
['CRS-016','Revit 2025 Essential Training for Structure','Mechanical + Civil Core','Software Lab','Stage 2','LinkedIn Learning','Eric Wing','https://www.linkedin.com/learning/revit-2025-essential-training-for-structure-imperial-and-metric'],
['CRS-012','The Engineering of Structures Around Us','Mechanical + Civil Core','Core','Stage 2','Coursera','Dartmouth','https://www.coursera.org/specializations/engineering-of-structures-around-us'],
['CRS-021','Design and Detailing of RCC Elements','Strength + Structures','Core','Stage 3','Coursera','L&T EduTech','https://www.coursera.org/learn/design-and-detailing-of-rcc-elements'],
['CRS-020','Design Basics of RCC Buildings','Strength + Structures','Core','Stage 3','Coursera','L&T EduTech','https://www.coursera.org/learn/design-basics-of-rcc-buildings'],
['CRS-022','Fundamentals of Mechanics of Materials','Strength + Structures','Practice','Stage 3','Udemy - مكتبتك','Vaibhav V. Khond','https://www.udemy.com/course/fundamentals-of-mechanics-of-materials/'],
['CRS-017','Mechanics of Materials I','Strength + Structures','Core','Stage 3','Coursera','Georgia Tech','https://www.coursera.org/learn/mechanics-1'],
['CRS-018','Mechanics of Materials II','Strength + Structures','Core','Stage 3','Coursera','Georgia Tech','https://www.coursera.org/learn/mechanics2'],
['CRS-019','Mechanics of Materials III: Beam Bending','Strength + Structures','Core','Stage 3','Coursera','Georgia Tech','https://www.coursera.org/learn/beam-bending'],
['CRS-024','Revit 2022-26: Reinforcement Details Shop Drawings from A-Z','Strength + Structures','Practice','Stage 3','Udemy - مكتبتك','RAKON GR.','https://www.udemy.com/course/revit-structure-2022-reinforcement-details-shop-drawings-from-a-z/'],
['CRS-023','Stress Analysis - Thin and Thick Cylinder','Strength + Structures','Practice','Stage 3','Udemy - مكتبتك','Eslam Shamso','https://www.udemy.com/course/stress-analysis-thin-and-thick-cylinder/'],
['CRS-030','Accelerated MATLAB','Dynamics + Geotechnical','Software Lab','Stage 4','LinkedIn Learning','Majlinda Qarri','https://www.linkedin.com/learning/accelerated-matlab'],
['CRS-025','Dynamics of Particles and Bodies in 2D Motion','Dynamics + Geotechnical','Core','Stage 4','Coursera','Georgia Tech','https://www.coursera.org/learn/dynamics'],
['CRS-029','Engineering Mechanics: Dynamics Part 2','Dynamics + Geotechnical','Practice','Stage 4','Udemy - مكتبتك','Cherish Qualls','https://www.udemy.com/course/engineering-mechanics-dynamics-rigid-bodies/'],
['CRS-027','Geotechnical Foundation Design','Dynamics + Geotechnical','Core','Stage 4','Coursera','L&T EduTech','https://www.coursera.org/specializations/geotechnical-foundation-design'],
['CRS-028','Introduction to Pile Foundation','Dynamics + Geotechnical','Core','Stage 4','Coursera','L&T EduTech','https://www.coursera.org/learn/introduction-of-pile-foundation'],
['CRS-026','Numerical Methods for Engineers','Dynamics + Geotechnical','Core','Stage 4','Coursera','HKUST','https://www.coursera.org/learn/numerical-methods-engineers'],
['CRS-037','Basics of Material Selection for Mechanical Design Engineers','Thermo + Fluids + Materials + Manufacturing','Practice','Stage 5','Udemy - مكتبتك','Mufaddal Rasheed','https://www.udemy.com/course/basics-of-material-selection-in-mechanical-design/'],
['CRS-032','Fundamentals of Fluid Power','Thermo + Fluids + Materials + Manufacturing','Core','Stage 5','Coursera','University of Minnesota','https://www.coursera.org/learn/fluid-power'],
['CRS-036','Fundamentals of Workshop Technology and Machine Tools','Thermo + Fluids + Materials + Manufacturing','Practice','Stage 5','Udemy - مكتبتك','J Aatish Rao','https://www.udemy.com/course/workshop-technology/'],
['CRS-031','Introduction to Thermodynamics','Thermo + Fluids + Materials + Manufacturing','Core','Stage 5','Coursera','University of Michigan','https://www.coursera.org/learn/thermodynamics-intro'],
['CRS-033','Material Behavior','Thermo + Fluids + Materials + Manufacturing','Core','Stage 5','Coursera','Georgia Tech','https://www.coursera.org/learn/material-behavior'],
['CRS-035','Pneumatics Fundamentals','Thermo + Fluids + Materials + Manufacturing','Practice','Stage 5','Udemy - مكتبتك','Dr. Prafulla Hatte','https://www.udemy.com/course/pneumatics-fundamentals/'],
['CRS-034','Thermodynamics for Engineering Students','Thermo + Fluids + Materials + Manufacturing','Practice','Stage 5','Udemy - مكتبتك','Cherish Qualls','https://www.udemy.com/course/thermodynamics-for-engineering-students/'],
['CRS-042','Building Smarter: BIM in Practice','Machine Design + Steel + BIM/MEP','Core','Stage 6','Coursera','L&T EduTech','https://www.coursera.org/specializations/building-smarter-bim-in-practice'],
['CRS-041','Design of Industrial Piping Systems','Machine Design + Steel + BIM/MEP','Core','Stage 6','Coursera','L&T EduTech','https://www.coursera.org/specializations/design-of-industrial-piping-systems'],
['CRS-044','Gear Fundamentals','Machine Design + Steel + BIM/MEP','Practice','Stage 6','Udemy - مكتبتك','Daniel Amevor','https://www.udemy.com/course/gear-fundamentals-and-tribology/'],
['CRS-043','Machine Design Basics - Shaft, Bearings & Gears','Machine Design + Steel + BIM/MEP','Practice','Stage 6','Udemy - مكتبتك','Mufaddal Rasheed','https://www.udemy.com/course/machine-element-design-basics-i-shaft-bearings-gears/'],
['CRS-039','Machine Design Part I','Machine Design + Steel + BIM/MEP','Core','Stage 6','Coursera','Georgia Tech','https://www.coursera.org/learn/machine-design1'],
['CRS-046','Navisworks Essential Training 2023','Machine Design + Steel + BIM/MEP','Software Lab','Stage 6','LinkedIn Learning','Eric Wing','https://www.linkedin.com/learning/navisworks-essential-training-2023'],
['CRS-045','Piping Design Engineering & Piping Isometrics Masterclass','Machine Design + Steel + BIM/MEP','Practice','Stage 6','Udemy - مكتبتك','WR Training Pro','https://www.udemy.com/course/piping-system-drafting-design-fabrication-with-isometrics/'],
['CRS-040','Steel Member Design: Theory to Practice','Machine Design + Steel + BIM/MEP','Core','Stage 6','Coursera','L&T EduTech','https://www.coursera.org/specializations/steel-member-design-theory-to-practice'],
['CRS-053','3 Phase Motor Control Bootcamp','Electrical + Electronics + Control','Practice','Stage 7','Udemy - مكتبتك','The Wiring Wizard','https://www.udemy.com/course/3-phase-motor-control-bootcamp/'],
['CRS-047','Basic Electronics','Electrical + Electronics + Control','Core','Stage 7','Coursera','BITS Pilani','https://www.coursera.org/learn/basic-electronics-odc'],
['CRS-050','Control Systems Analysis: Modeling of Dynamic Systems','Electrical + Electronics + Control','Core','Stage 7','Coursera','CU Boulder','https://www.coursera.org/learn/modeling-feedback-systems'],
['CRS-051','Fundamentals of Electrical Controls','Electrical + Electronics + Control','Practice','Stage 7','Udemy - مكتبتك','The Wiring Wizard','https://www.udemy.com/course/fundamentals-of-electrical-controls/'],
['CRS-052','Fundamentals of Electrical Instrumentation','Electrical + Electronics + Control','Practice','Stage 7','Udemy - مكتبتك','The Wiring Wizard','https://www.udemy.com/course/fundamentals-of-electrical-instrumentation/'],
['CRS-054','Introduction to PLC and Industrial Automation','Electrical + Electronics + Control','Software Lab','Stage 7','LinkedIn Learning','Zahraa Khalil','https://www.linkedin.com/learning/introduction-to-plc-and-industrial-automation'],
['CRS-048','Linear Circuits 1: DC Analysis','Electrical + Electronics + Control','Core','Stage 7','Coursera','Georgia Tech','https://www.coursera.org/learn/linear-circuits-dcanalysis'],
['CRS-049','Linear Circuits 2: AC Analysis','Electrical + Electronics + Control','Core','Stage 7','Coursera','Georgia Tech','https://www.coursera.org/learn/linear-circuits-ac-analysis'],
['CRS-055','Collaborative Robotics in Industry','Mechatronics + Automation + Robotics','Core','Stage 8','Coursera','L&T EduTech','https://www.coursera.org/specializations/collaborative-robotics-in-industry'],
['CRS-057','Introduction to Embedded Systems Software','Mechatronics + Automation + Robotics','Core','Stage 8','Coursera','CU Boulder','https://www.coursera.org/learn/introduction-embedded-systems'],
['CRS-056','Modern Robotics: Mechanics, Planning, and Control','Mechatronics + Automation + Robotics','Core','Stage 8','Coursera','Northwestern University','https://www.coursera.org/specializations/modernrobotics'],
['CRS-058','PLC Programming 100','Mechatronics + Automation + Robotics','Practice','Stage 8','Udemy - مكتبتك','Jonaz Sayson','https://www.udemy.com/course/plc-programming-100/'],
['CRS-060','Robotics & Mechatronics 1: Machine Theory & Production Lines','Mechatronics + Automation + Robotics','Practice','Stage 8','Udemy - مكتبتك','Mouhammad Hamsho','https://www.udemy.com/course/robotics-mechatronics-1-machine-design-theory/'],
['CRS-061','Robotics & Mechatronics 2: 3D Modelling & Machine Design','Mechatronics + Automation + Robotics','Practice','Stage 8','Udemy - مكتبتك','Mouhammad Hamsho','https://www.udemy.com/course/robotics-mechatronics-2-3d-cad-machine-design-fusion-360-conveyor-cnc/'],
['CRS-062B','Robotics & Mechatronics 3: Digital Twin Machines | Unity','Mechatronics + Automation + Robotics','Practice','Stage 8','Udemy - مكتبتك','Mouhammad Hamsho','https://www.udemy.com/course/robotics-mechatronics-3-digital-twin-machines-unity/'],
['CRS-059','Start Programming PLC in 3 Days - Siemens S7-1200','Mechatronics + Automation + Robotics','Practice','Stage 8','Udemy - مكتبتك','Jacob Biedulski','https://www.udemy.com/course/programming-plc-in-3-days-siemens-s7-1200-course/']
].map((x,i)=>({id:x[0]+'-'+i,courseId:x[0],title:x[1],track:x[2],role:x[3],stage:x[4],platform:x[5],provider:x[6],url:x[7],progress:0,status:'Not started'}));
